# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
[files]
extend-exclude = ["cfg/ytda.dne"]

[default.extend-words]
dne = "dne"
noet = "noet"
tru = "tru"
FLE = "FLE"
SER = "SER"
