#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022 David Rabkin
readonly REL=v0.9.20221213
readonly \
	BSH=https://github.com/rdavid/shellbase/releases/download/$REL/base.sh \
	DST=/usr/local/bin \
	TGT=/usr/local/bin/base.sh

# Starting point.
command -v curl >/dev/null 2>&1 || { printf >&2 Install\ curl.\\n; exit 12;}

# Uses Unix shell framework shellbase:
#  https://github.com/rdavid/shellbase/
# curl downloads shellbase content to stdout, eval sources it to the running
# environment.
eval "$(curl --location --silent $BSH)"
file_exists $TGT &&
	yes_to_continue \
		"$(sh $TGT --quiet --version)" \
		is installed. Install \
		"$BASE_VERSION"?
is_writable $DST || die $DST is not writable.
curl --location --output $TGT --silent $BSH ||
	die "Unable to install $BSH to $DST."
printf \
	'%s is installed to %s.\n' \
	"$(sh $TGT --quiet --version)" \
	$DST
