// Settings:
:toc: macro
:!toc-title:
// URLs:
:url-cv: http://cv.rabkin.co.il
:url-dig: https://linux.die.net/man/1/dig
:url-license: https://github.com/rdavid/toolbox/blob/master/LICENSE
:url-goredo: http://www.goredo.cypherpunks.ru/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-rdiff: https://github.com/rdiff-backup/rdiff-backup
:url-redo: http://cr.yp.to/redo.html
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shellbase: https://github.com/rdavid/shellbase
:url-shfmt: https://github.com/mvdan/sh
:url-speed: https://github.com/sivel/speedtest-cli
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-yt-dlp: https://github.com/yt-dlp/yt-dlp

= Toolbox

image:https://github.com/rdavid/toolbox/actions/workflows/lint.yml/badge.svg[linters,link=https://github.com/rdavid/toolbox/actions/workflows/lint.yml]
image:https://hitsofcode.com/github/rdavid/toolbox?branch=master&label=hits%20of%20code[hits of code,link=https://hitsofcode.com/view/github/rdavid/toolbox?branch=master]
image:https://img.shields.io/github/v/release/rdavid/toolbox?color=blue&label=%20&logo=semver&logoColor=white&style=flat[release),link=https://github.com/rdavid/toolbox/releases]
image:https://img.shields.io/github/license/rdavid/toolbox?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat[license,link=https://github.com/rdavid/toolbox/blob/master/LICENSE]

toc::[]

== About

The `toolbox` comprises a collection of Unix shell utilities designed for
regular use.
Each utility within the `toolbox` adheres to the POSIX,
`Portable Operating System Interface for uniX`, and operates within the Unix
shell framework known as {url-shellbase}[`shellbase`]:

 * link:app/bak[`bak`] serves as a wrapper for {url-rdiff}[`rdiff-backup`],
specifically designed to generate backups effectively.
* link:app/chowner[`chowner`] changes the owner and permissions on a directory.
* link:app/copyright[`copyright`] updates published years in copyrighted title.
* link:app/flactomp3[`flactomp3`] converts an audio to `mp3` with tags.
* link:app/ival[`ival`] Validates image files. `ival` stands for
`Image Validation`.
* link:app/myip[`myip`] continuously displays the external IP address, uses
{url-dig}[`dig`].
* link:app/pingo[`pingo`] adds timestamps to the ping command output.
* link:app/speed[`speed`] continuously displays download and upload internet
speeds, uses {url-speed}[`speedtest`].
* link:app/tru[`tru`] stands for transmission remote updater.
It removes a torrent with content and than adds it again.
It could be ran by `cron` to increase a ratio.
* link:app/ydata[`ydata`] is a wrapper on {url-yt-dlp}[`yt-dlp`]: downloads,
converts, renames and keeps safe. It could be ran by `cron`.

== Install

Ensure that you have added the directory `/usr/local/bin` to your `PATH`.

[,sh]
----
git clone git@github.com:rdavid/toolbox.git &&
  ./toolbox/app/install
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-shellcheck}[`shellcheck`], {url-shfmt}[`shfmt`], {url-typos}[`typos`],
{url-vale}[`vale`], {url-yamllint}[`yamllint`].

== License

`toolbox` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
