// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/toolbox?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/toolbox?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/toolbox?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test: https://github.com/rdavid/toolbox/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-arp-scan: https://github.com/royhills/arp-scan
:url-cv: http://cv.rabkin.co.il
:url-dig: https://linux.die.net/man/1/dig
:url-hoc: https://hitsofcode.com/view/github/rdavid/toolbox?branch=master
:url-license: https://github.com/rdavid/toolbox/blob/master/LICENSES/0BSD.txt
:url-ffmpeg: https://ffmpeg.org
:url-goredo: http://www.goredo.stargrave.org/INSTALL.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-rdiff: https://github.com/rdiff-backup/rdiff-backup
:url-redo: http://cr.yp.to/redo.html
:url-rsync: https://rsync.samba.org
:url-releases: https://github.com/rdavid/toolbox/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shellbase: https://github.com/rdavid/shellbase
:url-shfmt: https://github.com/mvdan/sh
:url-speed: https://github.com/sivel/speedtest-cli
:url-test: https://github.com/rdavid/toolbox/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-yt-dlp: https://github.com/yt-dlp/yt-dlp
:url-zizmor: https://github.com/zizmorcore/zizmor

= Toolbox

// The width is set to 71 characters, and the height is 7 lines. An ASCII art
// generator is used with the specific font Roman:
//  http://patorjk.com/software/taag/#p=display&f=Roman&t=toolbox
[,sh]
----
        .                       oooo   .o8                             
      .o8                       `888  "888                             
    .o888oo  .ooooo.   .ooooo.   888   888oooo.   .ooooo.  oooo    ooo 
      888   d88' `88b d88' `88b  888   d88' `88b d88' `88b  `88b..8P'  
      888   888   888 888   888  888   888   888 888   888    Y888'    
      888 . 888   888 888   888  888   888   888 888   888  .o8"'88b   
      "888" `Y8bod8P' `Y8bod8P' o888o  `Y8bod8P' `Y8bod8P' o88'   888o 
----

image:{img-test}[test,link={url-test}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release,link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

`toolbox` is a collection of Unix shell utilities for everyday use.
Each utility is a portable POSIX script built on the Unix shell framework
{url-shellbase}[`shellbase`]:

* link:app/bak[`bak`] wraps {url-rdiff}[`rdiff-backup`] to create
incremental backups.
* link:app/chowner[`chowner`] changes the owner and permissions on a directory.
* link:app/copyright[`copyright`] updates years in copyright notices.
* link:app/essid[`essid`] watches for Wi-Fi ESSID changes and reports them.
* link:app/flactomp3[`flactomp3`] converts audio files to `mp3` with tags.
* link:app/ival[`ival`] validates image files; the name stands for
Image Validation.
* link:app/myip[`myip`] continuously displays the external IP address using
{url-dig}[`dig`].
* link:app/pingo[`pingo`] adds timestamps to the ping command output.
* link:app/reel[`reel`] converts a video clip to a vertical (1080×1920) social
media reel using {url-ffmpeg}[`ffmpeg`], padding it with a blurred copy of
itself or, with `-c`, center-cropping it to fill the frame.
Accepts `-f` for input file, `-o` for output file, `-s` for start time,
`-u` for duration, and `-g` for a top and bottom gap in crop mode.
* link:app/remount[`remount`] remounts filesystems using a temporary `fstab`
configuration, then restores the permanent one.
* link:app/rsyncx[`rsyncx`] wraps {url-rsync}[`rsync`] and picks a safe option
set for the installed `rsync` version.
* link:app/scanner[`scanner`] detects whether a device with a given MAC
address is present on the local network using {url-arp-scan}[`arp-scan`].
* link:app/sift[`sift`] copies a random subset of files from a source
directory until the byte budget given by `-s|--size=N[K|M|G]`
(default `8G`) is reached.
Takes the source directory as the mandatory positional argument;
the destination defaults to the current directory and can be set with
`-o|--output=DIR`.
* link:app/speed[`speed`] continuously displays download and upload internet
speeds using {url-speed}[`speedtest`].
* link:app/tex[`tex`] compiles a TeX source file to PDF and opens the result.
* link:app/tru[`tru`] removes a torrent and its content, then adds it again
to increase the share ratio; the name stands for Transmission Remote Updater.
It can run under `cron`.
* link:app/ydata[`ydata`] wraps {url-yt-dlp}[`yt-dlp`]: it downloads,
converts, renames, and stores media safely. It can run under `cron`.

== Install

Ensure `/usr/local/bin` is in your `PATH`.

[,sh]
----
git clone git@github.com:rdavid/toolbox.git &&
  ./toolbox/app/install
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` runs whichever of the following linters are installed:
{url-actionlint}[`actionlint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`],
{url-zizmor}[`zizmor`].
It also parses every script with `dash -n` and `mksh -n` to catch syntax
errors and Bash-only constructs.

== License

{url-cv}[David Rabkin] holds the copyright to `toolbox` and distributes it
under the {url-license}[Zero-Clause BSD license].
