// Settings:
:toc: macro
:!toc-title:
// URLs:
:img-hoc: https://hitsofcode.com/github/rdavid/toolbox?branch=master&label=hits%20of%20code
:img-license: https://img.shields.io/github/license/rdavid/toolbox?color=blue&labelColor=gray&logo=freebsd&logoColor=lightgray&style=flat
:img-releases: https://img.shields.io/github/v/release/rdavid/toolbox?color=blue&label=%20&logo=semver&logoColor=white&style=flat
:img-test: https://github.com/rdavid/toolbox/actions/workflows/test.yml/badge.svg
:url-actionlint: https://github.com/rhysd/actionlint
:url-cv: http://cv.rabkin.co.il
:url-dig: https://linux.die.net/man/1/dig
:url-hoc: https://hitsofcode.com/view/github/rdavid/toolbox?branch=master
:url-license: https://github.com/rdavid/toolbox/blob/master/LICENSES/0BSD.txt
:url-goredo: http://www.goredo.cypherpunks.su/Install.html
:url-goredoer: https://github.com/rdavid/goredoer
:url-rdiff: https://github.com/rdiff-backup/rdiff-backup
:url-redo: http://cr.yp.to/redo.html
:url-releases: https://github.com/rdavid/toolbox/releases
:url-reuse: https://github.com/fsfe/reuse-action
:url-shellcheck: https://github.com/koalaman/shellcheck
:url-shellbase: https://github.com/rdavid/shellbase
:url-shfmt: https://github.com/mvdan/sh
:url-speed: https://github.com/sivel/speedtest-cli
:url-test: https://github.com/rdavid/toolbox/actions/workflows/test.yml
:url-typos: https://github.com/crate-ci/typos
:url-vale: https://vale.sh
:url-yamllint: https://github.com/adrienverge/yamllint
:url-yt-dlp: https://github.com/yt-dlp/yt-dlp

= Toolbox

// The width is set to 71 characters, and the height is 7 lines. An ASCII art
// generator is used with the specific font Roman:
//  http://patorjk.com/software/taag/#p=display&f=Roman&t=toolbox
[,sh]
----
        .                       oooo   .o8                             
      .o8                       `888  "888                             
    .o888oo  .ooooo.   .ooooo.   888   888oooo.   .ooooo.  oooo    ooo 
      888   d88' `88b d88' `88b  888   d88' `88b d88' `88b  `88b..8P'  
      888   888   888 888   888  888   888   888 888   888    Y888'    
      888 . 888   888 888   888  888   888   888 888   888  .o8"'88b   
      "888" `Y8bod8P' `Y8bod8P' o888o  `Y8bod8P' `Y8bod8P' o88'   888o 
----

image:{img-test}[test,link={url-test}]
image:{img-hoc}[hits of code,link={url-hoc}]
image:{img-releases}[release),link={url-releases}]
image:{img-license}[license,link={url-license}]

toc::[]

== About

The `toolbox` comprises a collection of Unix shell utilities designed for
regular use.
Each utility within the `toolbox` adheres to the POSIX,
`Portable Operating System Interface for uniX`, and operates within the Unix
shell framework known as {url-shellbase}[`shellbase`]:

 * link:app/bak[`bak`] serves as a wrapper for {url-rdiff}[`rdiff-backup`],
specifically designed to generate backups effectively.
* link:app/chowner[`chowner`] changes the owner and permissions on a directory.
* link:app/copyright[`copyright`] updates published years in copyrighted title.
* link:app/flactomp3[`flactomp3`] converts an audio to `mp3` with tags.
* link:app/ival[`ival`] Validates image files. `ival` stands for
`Image Validation`.
* link:app/myip[`myip`] continuously displays the external IP address, uses
{url-dig}[`dig`].
* link:app/pingo[`pingo`] adds timestamps to the ping command output.
* link:app/speed[`speed`] continuously displays download and upload internet
speeds, uses {url-speed}[`speedtest`].
* link:app/tru[`tru`] stands for transmission remote updater.
It removes a torrent with content and than adds it again.
It could be ran by `cron` to increase a ratio.
* link:app/ydata[`ydata`] is a wrapper on {url-yt-dlp}[`yt-dlp`]: downloads,
converts, renames and keeps safe. It could be ran by `cron`.

== Install

Ensure that you have added the directory `/usr/local/bin` to your `PATH`.

[,sh]
----
git clone git@github.com:rdavid/toolbox.git &&
  ./toolbox/app/install
----

== Test

The project uses Daniel J. Bernstein's build system {url-redo}[`redo`].
You can install Sergey Matveev's {url-goredo}[`goredo`] implementation.
`redo lint` applies the following linters to the source files:
{url-actionlint}[`actionlint`],
{url-reuse}[`reuse`],
{url-shellcheck}[`shellcheck`],
{url-shfmt}[`shfmt`],
{url-typos}[`typos`],
{url-vale}[`vale`],
{url-yamllint}[`yamllint`].

== License

`toolbox` is copyright {url-cv}[David Rabkin] and available under a
{url-license}[Zero-Clause BSD license].
