#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2019-2023 David Rabkin
# Sets owner to a user from the first argument, set right permissions for files
# and directories started from the seconds argument.
# shellcheck disable=SC1091,SC2034 # File not following, appears unused.
readonly \
	BASE_APP_USAGE='Usage: chowner user directory.' \
	BASE_APP_VERSION=0.9.20230626 \
	BASE_MIN_VERSION=0.9.20230312
. base.sh
beroot
[ "$#" -eq 2 ] || die "$BASE_APP_USAGE"
readonly \
	DIR="$2" \
	USR="$1"
user_exists "$USR" || die "$USR": No such user.
file_exists "$DIR" || die "$DIR": No such file or directory.
iswritable "$DIR" || die "$DIR" is not writable.
chown -R "$USR" "$DIR"
find "$DIR" -type d -exec chmod 755 {} \;
find "$DIR" -type f -exec chmod 644 {} \;
log The owner of "$DIR" is changed to "$USR".
