#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2020-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Watches for Wi-Fi ESSID changes and reports them.
#
# shellcheck disable=SC1091,SC2034 # File not following, appears unused.
readonly BASE_APP_VERSION=0.9.20260603
. base.sh
readonly \
	CUR=/"$BASE_WIP"/cur \
	OLD=/"$BASE_WIP"/old

list() {
	iwlist wlan0 s | grep ESSID | tr -s ' ' | cut -d':' -f2 >"$CUR"
}

copy() {
	cp -f "$CUR" "$OLD"
}

pause() {
	sleep 5
}

comp() {
	out='ESSID list is'
	changed="$(diff -y --suppress-common-lines "$CUR" "$OLD" | wc -l)"
	if [ "$changed" -ne '0' ]; then
		out="$out changed on $changed. Alert!"
	else
		out="$out not changed."
	fi
	log "$out"
}

beroot
validate_cmd iwlist
list
while :; do
	pause
	copy
	list
	comp
done
