#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2020-2023 David Rabkin
# Validates image files.
# shellcheck disable=SC1091,SC2034 # File not following, variable unused.
readonly \
	BASE_APP_VERSION=0.9.20230621 \
	BASE_MIN_VERSION=0.9.20230606
. base.sh
validate_cmd convert
[ "$#" -eq 1 ] || die Usage: "$BASE_IAM" DIRECTORY
[ -r "$1" ] || die Unable to read "$1".
find "$1" -type f \
	\( -name \*.jpg -o -name \*.nef -o -name \*.raf -o -name \*.heic \) |
	while read -r img; do
		convert "$img" null >/dev/null 2>&1 || loge File is corrupted: "$img".
		log "$img" is OK.
	done
