#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2021-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# -*- coding: utf-8 -*-

import base64
import click
import pyperclip
import pyotp
import os
import sys
from subprocess import Popen, PIPE
from configobj import ConfigObj

TOP = 'PARAMS'

if __name__ == '__main__':
	if len(sys.argv) != 2:
		print("Usage: %s <config-file>" % sys.argv[0])
		sys.exit(1)
	cfg_path = sys.argv[1]
	if not os.path.isfile(cfg_path):
		print("Unable to find configuration file %s." % cfg_path)
		sys.exit(1)
	cfg = ConfigObj(cfg_path)
	fil = cfg[TOP]['shared']
	if not os.path.isfile(fil):
		print("Unable to find shared configuration file %s." % fil)
		sys.exit(1)
	shr = ConfigObj(fil)
	sec = cfg[TOP]['secret']
	pin = cfg[TOP]['pin']
	cnt = int(shr[TOP]['counter'])
	otp = pyotp.HOTP(sec)
	res = r"%s%s" % (pin, int(otp.at(cnt)))
	pyperclip.copy(res)
	cnt += 1
	shr[TOP]['counter'] = cnt
	shr.write()
	print("The counter is set to %s." % str(cnt))
