#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2022-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# Adds timestamps to the ping command output.
#
# shellcheck disable=SC1091,SC2034 # File not following, appears unused.
set -- "$@" --quiet
readonly BASE_APP_VERSION=0.9.20260608
. base.sh

# Validates the environment and runs ping with timestamped output.
main() {
	validate "$@"
	process
}

# Runs ping with timestamped output.
process() {
	{
		ping "$TGT" 2>&1 1>&3 3>&- | tologe
	} 3>&1 1>&2 | totsout
}

# Validates the environment and sets TGT.
validate() {
	validate_cmd ping
	[ $# -ge 1 ] || die pingo: try pingo [host]
	readonly TGT="$1"
}

# Entry point.
main "$@"
