#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2022-2024 David Rabkin
# Adds timestamps to the ping command output.
# shellcheck disable=SC1091,SC2034 # File not following, appears unused.
set -- "$@" --quiet
readonly \
	BASE_APP_VERSION=0.9.20240806 \
	BASE_MIN_VERSION=0.9.20231212
. base.sh
[ $# -ge 1 ] || die pingo: try pingo [network resource]
{ ping "$1" 2>&1 1>&3 3>&- | tologe; } 3>&1 1>&2 | totsout
