#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2020-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# shellcheck disable=SC1091 # File not following.
. base.sh
[ "$#" -eq 1 ] || die tex: try tex [file name]
[ -r "$1" ] || die Unable to read from source "$1".
validate_cmd tex dvipdfm
NME=$(basename -- "$1")

# Makes sure that source filename has tex extension.
[ 'tex' = "${NME##*.}" ] || die Source file "$1" should have .tex extension.

# Extracts file name only.
NME="${NME%.*}"
readonly \
	DVI="$NME.dvi" \
	LOG="$NME.log" \
	NME \
	PDF="$NME.pdf" \
	TEX="$NME.tex"

# Do not worry about file cleaning on exit. Garbage collector will remove the
# temporarily directory.
cp "$1" "$BASE_WIP"
cd "$BASE_WIP" || die
if ! tex --interaction=batchmode "./$TEX" >/dev/null 2>&1; then
	cp "./$LOG" "$OLDPWD"
	die See "$LOG" for errors.
fi
dvipdfm "./$DVI" >/dev/null 2>&1
cp "./$PDF" "$OLDPWD"
open "$OLDPWD/$PDF"
