#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# SPDX-FileCopyrightText: 2020-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
#
# shellcheck disable=SC1091 # File not following.
. base.sh
[ "$#" -eq 1 ] || die tex: try tex [file name]
isreadable "$1" || die Unable to read file "$1".
validate_cmd dvipdfm sed tex
NME=$(basename -- "$1")

# Makes sure that source filename has .tex extension.
case "$NME" in
*.tex) : ;;
*) die Source file "$1" should have .tex extension. ;;
esac

# Extracts file name only.
NME="$(printf %s "$NME" | sed 's/\.[^./]*$//')"
readonly \
	DVI="$NME".dvi \
	LOG="$NME".log \
	NME \
	PDF="$NME".pdf \
	TEX="$NME".tex

# Do not worry about file cleaning on exit. Garbage collector will remove the
# temporarily directory.
cp "$1" "$BASE_WIP"
cd "$BASE_WIP" || die
if ! tex --interaction=batchmode "./$TEX" >/dev/null 2>&1; then
	cp "./$LOG" "$OLDPWD"
	die See "$LOG" for errors.
fi
dvipdfm "./$DVI" >/dev/null 2>&1
cp "./$PDF" "$OLDPWD"
open "$OLDPWD/$PDF"
