#!/bin/sh
# vi:et lbr noet sw=2 ts=2 tw=79 wrap
# Copyright 2020-2023 David Rabkin
# tru stands for Transmission Remote Updater. The script removes a torrent with
# content and than adds it again. It is usefull to automatically increase a
# ratio.
# The script uses local variables which are not POSIX but supported by most
# shells, see more:
#  https://stackoverflow.com/questions/18597697/posix-compliant-way-to-scope-variables-to-a-function-in-a-shell-script
# shellcheck disable=SC3043 # Uses local variables.
# shellcheck disable=SC1091,SC2034 # File not following, appears unused.
readonly BASE_APP_VERSION=0.9.20230306
. base.sh

# Looks for torrent ID by torrent name extracted from torrent file name.
# Continues if the ID is not existed.
main() {
	validation "$@"
	local tid
	tid=$(tid) || die
	if [ -n "$tid" ]; then
		{
			# shellcheck disable=SC2086 # Double quote to prevent globbing.
			transmission-remote "$SER" $AUT --torrent "$tid" --remove-and-delete \
				2>&1 1>&3 3>&- | to_loge
		} \
			3>&1 1>&2 | to_log
		log "$NME $tid is removed from $SER."
	fi

	# Adds torrent file name to torrent server.
	{
		# shellcheck disable=SC2086 # Double quote to prevent globbing.
		transmission-remote "$SER" $AUT --add "$TOR" \
			2>&1 1>&3 3>&- | to_loge
	} \
		3>&1 1>&2 | to_log

	# Verifies that a torrent was added.
	tid=$(tid) || die
	log "$NME $tid is added to $SER."
}

# Looks for torrent ID by torrent file name.
tid() {
	local out

	# shellcheck disable=SC2086 # Double quote to prevent globbing.
	out="$(transmission-remote "$SER" $AUT --list 2>&1)" ||
		die Unable to communicate with "$SER": "$out"
	out="$(printf %s "$out" | grep "$NME")"
	[ -n "$out" ] || {
		logw There is no "$NME" in "$SER".
		return 0
	}
	out="$(printf %s "$out" | awk '{print $1}')"
	[ -n "$out" ] || die Wrong format: "$out".
	printf %s "$out"
}

validation() {
	validate_cmd awk nc tr transmission-remote transmission-show
	[ "$#" -eq 3 ] || die Usage: tru host:port user:pass torrent-file.

	# Single : means there is no authentication data.
	if [ "$2" != : ]; then
		AUT="--auth $2"
	else
		AUT=''
	fi
	readonly \
		AUT \
		SER="$1" \
		TOR="$3"

	# Prepares host and port to be nc command parameters. Validates the first
	# parameter host:port.
	local out prm
	prm="$(printf %s "$SER" | tr : \ )"

	# shellcheck disable=SC2086 # Double quote to prevent globbing.
	nc -z $prm >/dev/null 2>&1 || die "$prm" is not available.

	# Validates third parameter full torrent file name.
	is_readable "$TOR" || die
	out="$(transmission-show "$TOR")" || die Unable to read "$TOR": "$out"
	NME="$(printf %s "$out" | grep Name: | head -1 | cut -c 7-)"
	readonly NME
	[ -n "$NME" ] || die Unable to extract name from "$TOR": "$out"
}

# Starting point.
main "$@"
