# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# Lints the GitHub Actions workflows. The downloader reports the linter path
# as a step output, which the final step reads through an environment variable
# rather than expanding inline, so the run block stays free of template
# injection.
---
name: actionlint
'on':
  pull_request:
    paths: &paths
      - .github/workflows/**
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  actionlint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - id: get
        run: |
          ver=1.7.12
          srv=https://raw.githubusercontent.com/rhysd/actionlint
          curl \
            --fail \
            --location \
            --show-error \
            --silent \
            "$srv/v$ver/scripts/download-actionlint.bash" |
            bash -s "$ver"
      - env:
          EXECUTABLE: ${{ steps.get.outputs.executable }}
        run: '"$EXECUTABLE"'
