---
name: linters
'on': push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: ./*.do ./app/*
          ignore_names: pass
      - uses: mfinelli/setup-shfmt@v3
      - run: shfmt -d ./*.do ./app/[bcefimrsty]*
      - uses: crate-ci/typos@master
      - uses: errata-ai/vale-action@reviewdog
        with:
          fail_on_error: true
          files: README.adoc
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/*.yml .github/workflows/*.yml
          strict: true
