---
name: linters
'on': push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: nosborn/github-action-markdown-cli@v3.3.0
        with:
          files: .
      - uses: ludeeus/action-shellcheck@master
        with:
          additional_files: app/*
          ignore_names: pass
      - uses: mfinelli/setup-shfmt@v2
      - run: shfmt -d app
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/*.yml .github/workflows/*.yml
          strict: true
