---
name: linters
'on': [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ludeeus/action-shellcheck@master
        with:
          ignore_names: pass
          scandir: app
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .github/workflows/*.yml
