# SPDX-FileCopyrightText: 2025 David Rabkin
# SPDX-License-Identifier: 0BSD
---
name: shfmt
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  shfmt:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v5
      - uses: mfinelli/setup-shfmt@v4
      - run: shfmt -d ./*.do ./app/[bcefimrsty]*
