# SPDX-FileCopyrightText: 2023-2025 David Rabkin
# SPDX-License-Identifier: 0BSD
# This workflow has limitations -- Ubuntu lacks a redo package.
---
name: test
'on':
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  BASE_REL: 0.9.20250808
  BASE_SRC: https://github.com/rdavid/shellbase/archive/refs/tags/v0.9.20250808.tar.gz # yamllint disable-line
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-13
          - macos-14
          - macos-15
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - run: |
          brew install goredo
          curl --location --silent "$BASE_SRC" |
            tar \
              --directory /usr/local/bin \
              --extract \
              --gzip \
              --strip-components=2 \
              shellbase-"$BASE_REL"/lib/base.sh
          redo -xx
