# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# This workflow has limitations -- Ubuntu lacks a redo package.
---
name: test
'on':
  pull_request:
    paths: &paths
      - '**/*.do'
      - app/**
      - cfg/**
      - README.adoc
      - .github/workflows/test.yml
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - run: |
          ver=0.9.20260404
          srv=https://github.com/rdavid/shellbase
          brew install goredo
          curl \
            --location \
            --silent \
            "$srv/archive/refs/tags/v$ver.tar.gz" |
            tar \
              --directory /usr/local/bin \
              --extract \
              --gzip \
              --strip-components=2 \
              shellbase-"$ver"/lib/base.sh
          redo -xx
