# SPDX-FileCopyrightText: 2023-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# This workflow has limitations -- Ubuntu lacks a redo package.
---
name: test
'on':
  pull_request:
  push:
    branches: [master]
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
env:
  BASE_REL: 0.9.20260404
  BASE_SRC: https://github.com/rdavid/shellbase/archive/refs/tags/v0.9.20260404.tar.gz # yamllint disable-line
jobs:
  test:
    strategy:
      matrix:
        os:
          - macos-14
          - macos-15
          - macos-15-intel
    runs-on: ${{ matrix.os }}
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v6.0.3
      - run: |
          brew upgrade
          brew install goredo
          curl --location --silent "$BASE_SRC" |
            tar \
              --directory /usr/local/bin \
              --extract \
              --gzip \
              --strip-components=2 \
              shellbase-"$BASE_REL"/lib/base.sh
          redo -xx
