# SPDX-FileCopyrightText: 2025-2026 David Rabkin
# SPDX-License-Identifier: 0BSD
# The trigger mirrors the lint scope below: only YAML directly under .github
# and .github/workflows. The vendored Vale rules under .github/styles are not
# linted here, so a broad .github/**/*.yml pattern would fire the job on style
# changes it never checks.
---
name: yamllint
'on':
  pull_request:
    paths: &paths
      - .github/*.yml
      - .github/workflows/*.yml
  push:
    branches: [master]
    paths: *paths
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.event_name == 'pull_request' }}
jobs:
  yamllint:
    runs-on: ubuntu-24.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v7.0.0
        with:
          persist-credentials: false
      - uses: ibiqlik/action-yamllint@v3.1.1
        with:
          file_or_dir: >
            ./.github/*.yml
            ./.github/workflows/*.yml
          strict: true
